### ISSUE TITLE
Better horizontal scrolling support for tables

### ISSUE THREAD

**Issue by mattbdean** [mattbdean/Helium#10]
This is primarily an issue with how Helium uses [`@swimlane/ngx-datatable`](https://github.com/swimlane/ngx-datatable). There is a [`scrollbarH`](https://swimlane.gitbooks.io/ngx-datatable/api/table/inputs.html#scrollbarh) property binding, but if that isn't sufficient, we could always reimplement the datatable using `@angular/material`'s up and coming support.

**Comment by boazmohar** [comment]
Try HScroll + resizing the table on `resize` table event.
