### ISSUE TITLE
Have a now button for the date & datetime fields in a form

### ISSUE THREAD

**Issue by boazmohar** [mattbdean/Helium#143]
There are some cases where you have a start and end date / datetime fields in a form.
The form is left open while a session / surgery is ongoing.
It would be convenient to add a button that would fill the current date / datetime into the field.

This only effects the date / datetime fields in a form.

**Comment by mattbdean** [comment]
[Here's what it looks like on master](https://gfycat.com/DecentPertinentCranefly)
