### ISSUE TITLE
"Insert like" button in DatatableComponent

### ISSUE THREAD

**Issue by mattbdean** [mattbdean/Helium#15]
This button should appear for every row in the datatable when it's hovered over. When clicked, it should produce a form whose values are pre-populated with the selected row.

- [x] 1st level - only master tables
- [ ] 2nd level - master tables and part tables

**Comment by boazmohar** [comment]
@mattbdean For me this doesn't copy the primary keys, is that intended?
I don't get any errors in the console.

**Comment by mattbdean** [comment]
This is intended since primary keys have to be unique. If we copied the entire row into a new form and the user pressed submit, there would be an error. This way we save the user the trouble of manually removing that field.

**Comment by boazmohar** [comment]
I think we should copy all the keys.
If I have a table with a lot of foreign keys as primary keys and I want to change only one key and not have to copy all the others.
What do you think?
Error messages will be taken care of in #5

**Comment by mattbdean** [comment]
See #29

**Comment by boazmohar** [comment]
- [ ] get all table names
- [ ] see if it a master (same name + '__')
- [ ] query part tables based on primary keys - need server side filtering #11.
- [ ] create the form
