### ISSUE TITLE
Support multiple schemas

### ISSUE THREAD

**Issue by mattbdean** [mattbdean/Helium#28]
For example,

`GET /api/v1/tables/:table` would fetch the same data as `GET /api/v1/schemas/:schema/:table` where `:schema` is the name of the `database` key in `db.conf.json`. Other endpoints are renamed similarly.

```
/api/v1
  GET /schemas
  GET /tables                   --> /schemas/:schema
  GET /tables/:name             --> /schemas/:schema/:table
  GET /tables/:name/column/:col --> /schemas/:schema/:table/column/:col
  GET /tables/:name/data        --> /schemas/:schema/:table/data
  PUT /tables/:name/data        --> /schemas/:schema/:table/data
```

Angular routing would follow the same pattern.

On the website, the very top of the sidenav would contain a dropdown for schema selection.

**Comment by LiuDaveLiu** [comment]
Has this issue been resolved? We would like to start using Helium for our current pipeline with multiple schema.

**Comment by mattbdean** [comment]
Unfortunately no, this is a rather large issue. Session/DB connection management requires a major overhaul of both the server and client since I wrote Helium assuming only one schema was involved at a time.

If you'd like to check out the progress, all work is being done on the [`schema-support`](https://github.com/mattbdean/Helium/commits/schema-support) branch.

**Comment by mattbdean** [comment]
@LiuDaveLiu @boazmohar Quick update: the API is ready to handle multiple connections to multiple databases/schemas from multiple users (see [this massive commit](https://github.com/mattbdean/Helium/commit/14aff001edf884a3cfa182f54e84d505a2205c13)). The client shouldn't take as long to update!
