### ISSUE TITLE
ENUM field has no header

### ISSUE THREAD

**Issue by boazmohar** [mattbdean/Helium#35]
`enum` field from datajoint definition in the form field has no header.
```
sex                 : enum('M','F','Unknown')
```
I only see a dropdown with M, F, Unknown
Expected a `sex` header as well

**Comment by mattbdean** [comment]
What do you mean by "has no header?" Do you mean that there's no label for the enum input?

**Comment by boazmohar** [comment]
Yes I can’t see the column name.

Boaz

**Comment by mattbdean** [comment]
Does the issue still persist for you? It works on `master` for me.

**Comment by boazmohar** [comment]
Is is partially fixed. Before entering data there is label, but as other columns the label remins after you enter data here the label is [gone](https://www.dropbox.com/s/06zd00qp528oev8/Screenshot%202017-12-26%2020.16.52.png?dl=0 ).
Not a huge deal, if there is no easy fix, we will push it to 1.0.0.

**Comment by mattbdean** [comment]
This is actually how the dropdown is supposed to work. If we really want that label to be there when a value is selected, I could change the dropdown to an autocomplete.

**Comment by mattbdean** [comment]
Ignore me closing the issue, I put the wrong issue number in the commit message

**Comment by boazmohar** [comment]
No leave it as a drop-down, an autocomplete will make the user think these are only suggested values.
