### ISSUE TITLE
no such file 'db.conf.json'

### ISSUE THREAD

**Issue by LiuDaveLiu** [mattbdean/Helium#37]
I am getting an error Could not connect to database: ENOENT: no such file, open 'Helium\dist\db.conf.json'

**Comment by mattbdean** [comment]
Please `git pull` and try again

**Comment by LiuDaveLiu** [comment]
Sorry, I just saw that you removed the need for db.conf.json.

I am getting the following error when building the website.

ERROR in ng:///C:/Users/liul.HHMI/Desktop/Helium/client/app/app.component.html (
3,39): Property 'formGroup' is private and only accessible within class 'AppComp
onent'.
ERROR in C:/Users/liul.HHMI/Desktop/Helium/client/app/core/table.service.ts (91,
51): Argument of type '{ params: HttpParams; headers: { 'X-API-Key': string; };
observe: "response"; }' is not assignable to parameter of type '{ headers?: Http
Headers; observe?: "body"; params?: HttpParams; reportProgress?: boolean; respon
s...'.
  Types of property 'headers' are incompatible.
    Type '{ 'X-API-Key': string; }' is not assignable to type 'HttpHeaders'.
      Property 'headers' is missing in type '{ 'X-API-Key': string; }'.
error Command failed with exit code 1.

**Comment by mattbdean** [comment]
I've managed to fix the first error, but I can't seem to replicate the second one. Could you do a clean rebuild with the latest commits on `master` and see if it persists?

```
$ git pull
$ rm -r node_modules
$ yarn install
$ yarn prod
```

**Comment by LiuDaveLiu** [comment]
I did the rebuilt and the error was gone. Thank you very much.
