### ISSUE TITLE
On page refresh the sidebar is not returning to the current table view

### ISSUE THREAD

**Issue by LiuDaveLiu** [mattbdean/Helium#39]
If I by default land on schema\table, then navigate to schema2\table2 and refresh the page the table view goes to  schema2\table2 but the sidebar view returns to schema\table.
![image](https://user-images.githubusercontent.com/8761973/34364543-fdbe77b2-ea54-11e7-8021-2b60ca94562d.png)

**Comment by mattbdean** [comment]
Should be an easy fix

**Comment by LiuDaveLiu** [comment]
This issue still persist for me. It's annoying when I have to navigate through a schema and the sidebar is not synced.

**Comment by mattbdean** [comment]
I can't reproduce. Can you pull and do a fresh build?
