### ISSUE TITLE
On navigation to a table headers are not the right width

### ISSUE THREAD

**Issue by LiuDaveLiu** [mattbdean/Helium#40]
After resizing the window, the column widths are fine.
before
![image](https://user-images.githubusercontent.com/8761973/34364668-19cce8fc-ea56-11e7-83a8-cffea74ecc8f.png)
after
![image](https://user-images.githubusercontent.com/8761973/34364670-24a01dee-ea56-11e7-8c9a-2ff9c2ee907d.png)

**Comment by mattbdean** [comment]
This is gonna be an issue with a recent `@swimlane/ngx-datatable` update, I'll check it out
