### ISSUE TITLE
Part table can have different master keys

### ISSUE THREAD

**Issue by LiuDaveLiu** [mattbdean/Helium#41]
Part table keys that are part of the master table should always be hidden/ grayed out. 
We can submit a master + part table referring to different master keys:
![image](https://user-images.githubusercontent.com/8761973/34364841-caa5ee16-ea57-11e7-9eaa-1ff72db10d20.png)

When we navigate to this table we also get this error on the [console](https://gist.github.com/LiuDaveLiu/a9e686b2f7d01e615194432009136e06)

Tell us if you need permissions to the server

**Comment by mattbdean** [comment]
Could you reproduce the error with `yarn dev`? That'll produce a better stacktrace.

And yes can you send me the db info on slack?

**Comment by boazmohar** [comment]
[spinevis.int.janelia.org-1514327147141_form_part_table.log](https://github.com/mattbdean/Helium/files/1587972/spinevis.int.janelia.org-1514327147141_form_part_table.log)

**Comment by mattbdean** [comment]
What schema/table is this?

**Comment by boazmohar** [comment]
You can also look at `/forms/boazmohar_experiment/session`

**Comment by mattbdean** [comment]
This is another race condition. The code assumes that metadata for the master table will come back before the metadata for the part tables.

The part table foreign keys that reference primary keys of their master tables are automatically hidden. The error being thrown stops execution before they can be bound to the master primary key and hidden.

Can fix!

**Comment by mattbdean** [comment]
Fixed, [here's what it looks like now](https://i.imgur.com/UBdNRbV.png)

**Comment by boazmohar** [comment]
@mattbdean Great work! works for me as well 🎉 
Whats next #11?

**Comment by mattbdean** [comment]
Will do! I generally create a feature branch for any change that takes more than a few commits to be useful.

Datatable filtering is next on the docket.
