### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by LiuDaveLiu** [mattbdean/Helium#43]
I just got Helium on my Macbook, but the login button on the login page is grayed out with no obvious error messages.

**Comment by boazmohar** [comment]
Can you restart the server using yarn dev.
Then open developer tools in your browser and go to the console and refresh the page. Is there an error message in the console?

**Comment by LiuDaveLiu** [comment]
Yes, the error is [here](https://gist.github.com/LiuDaveLiu/b7f230ddfc1c8d0354db79327e045045).

**Comment by mattbdean** [comment]
What browser and version of the browser are you using?

**Comment by LiuDaveLiu** [comment]
I thought it was a browser issue as well, but the error persists on Safari, Chrome, and Firefox.

**Comment by mattbdean** [comment]
Very strange. It passes on my local machine (Ubuntu 17.10) and on CI (Ubuntu 14.04), Maybe it's Mac specific? What version of the OS are you running? What version does `chrome://version` report?

**Comment by LiuDaveLiu** [comment]
I am running OS Version 10.13.2. Chrome version 60.0.3112.101

**Comment by boazmohar** [comment]
I am not seeing that error but I am running OS 10.12.6, I tried Opera, Chrome (64.0.3282.39) and Firefox all work fine, maybe update Chrome?

**Comment by LiuDaveLiu** [comment]
Updating Chrome solved the problem.

**Comment by boazmohar** [comment]
Had the same thing BTW, `yarn install` didn't get the fact that packages changed and deleting the repo and cloning helped me.
