### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by mattbdean** [mattbdean/Helium#46]
A Docker image is the ideal way to package and deploy this app in my opinion. We would have to use something like [redis](https://redis.io/) to store, fetch, and delete API keys. This would also allow Helium to scale by adding as many containers as necessary.

The Helium + redis containers can be organized using [Docker Compose](https://docs.docker.com/compose/).

I'd like this to be a beta feature so people won't have to mess with git. Ideally, all people would have to do to get Helium up and running is run one command.

Maybe for the beta we could create a non-scalable image and host it on [Docker Hub](https://hub.docker.com/). Then for 1.0.0 we could integrate scalability w/ Docker Compose and redis.
 
See also: #59

**Comment by boazmohar** [comment]
I think that is a great idea, it is a hassle to have them mess with git.
However, I am not sure we need it for the beta.
I currently have it running on an internal server in Janelia (spinevis.int.jenalia.org:3000) so we could just point people there.
If there will be interest outside Janelia we could go that route.
Or am I missing some other Docker advantages?

**Comment by mattbdean** [comment]
> Or am I missing some other Docker advantages?

Scalability, but I'm not sure we'll need that quite yet.

**Comment by mattbdean** [comment]
The e2e tests should also be run against the docker image before deploying.

**Comment by mattbdean** [comment]
Currently being worked on in the [`docker`](https://github.com/mattbdean/Helium/tree/docker) branch
