### ISSUE TITLE
Part table with complex foreign key still showing

### ISSUE THREAD

**Issue by boazmohar** [mattbdean/Helium#49]
I have a part table that is part of a master table with a complex master key.
I still see that master key in the part table form:
<img width="1260" alt="screenshot 2018-01-06 18 13 36" src="https://user-images.githubusercontent.com/9434009/34644888-b56d0822-f30d-11e7-88c1-bf549b781ef5.png">

In this example subject_id and fov_id are the master keys for both tables.
They should not show up on the bottom form, right?

I don't see that if I look at another part table that has a single key:
<img width="1252" alt="screenshot 2018-01-06 18 20 52" src="https://user-images.githubusercontent.com/9434009/34644908-6b399bb6-f30e-11e7-9f87-7aea360640f8.png">

I hope this is not a problem with my `datajoint` schema, @mattbdean could you also check?

**Comment by boazmohar** [comment]
My bug, found it, it is working now.

**Comment by mattbdean** [comment]
What was the fix?

**Comment by boazmohar** [comment]
I had an error in the schema, referring to the same table twice, once in the master and once outside.
