### ISSUE TITLE
Auto-increment attributes should be hidden

### ISSUE THREAD

**Issue by arsenyf** [mattbdean/Helium#64]
If an attribute has an auto-increment property, Helium doesn't hide it when one attempts to insert a new entry using the + option. In principle, the user should not be able to enter manually attributes that are auto-incremented.

I created a dummy schema "map_arsenytest" with the attribute session_uid being auto-incremented.

**Comment by mattbdean** [comment]
For most people this would probably be fine. However there are some edge cases in which users will want to set this value manually. I think the more flexible solution here would be to calculate the next value and prefill the form control with that value. If the user ends up ignoring it, all we've given up is a little bit of space.

**Comment by mattbdean** [comment]
The next value of auto increment can be found in `information_schema.TABLES`, there is an `AUTO_INCREMENT` column that contains the next value.
